version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /salesforce/adconnect # this is necessary for Salesforce to post to without login.
  script: auth.app
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
  
- url: /.*
  script: auth.app
  login: required
  secure: always

